INCLUDE 'EMU8086.INC'
.MODEL SMALL
.STACK 200H  
 
.DATA
 COUNT DB 0
 
.CODE 
MAIN PROC
    MOV AX, @DATA
    MOV DS, AX
    
    XOR BX,BX
    MOV CL,4; WE WILL HAVE TO SHIFT 4 TIMES THIS TIME
    
    PRINT "ENTER HEX NUMBERS: "
    MOV AH,1
    FOR1:
    INT 21H
    CMP AL,0DH
    JE END_FOR1
    
    CMP AL,41H ; CHECKING IF IT IS A-F
    JGE LETTER
    
    ;FOR DIGITS:
    SUB AL,48
    JMP SHIFT
    
    LETTER:
    SUB AL,37H
    
    SHIFT:
    SHL BX,CL
    OR BL,AL
    
   JMP FOR1
    
END_FOR1:
PRINTN
PRINT "OUTPUT: "

XOR CH,CH
MOV CX,4
MOV AH,2

FOR2: ; SHIFTING TO THE LOWER 8 BITS. SO THAT ENTIRE NUMBER REPRESNTS FIRST 2 DIGITS OF OUR HEX NUMBER 
    MOV DL,BH
    SHR DL,4 ; keeping ony 4 bits in DL
    SHL BX,4
       
    CMP DL,10 ; CHECKING IF LETTER OR DIGIT
    JGE LETTER2
    
    ;OUTPUT:
    ADD DL,48
    INT 21H
    JMP END_OF_LOOP2
    
    LETTER2:
    ADD DL,55
    INT 21H
    
    END_OF_LOOP2:
    LOOP FOR2
    
    MOV AH,4CH
    INT 21H  
    MAIN ENDP
ENDP