 INCLUDE 'EMU8086.INC'
.MODEL SMALL
.STACK 200H  
 
.DATA

.CODE 
MAIN PROC
    MOV AX, @DATA
    MOV DS, AX
    
    MOV BH,5; SIZE OF THE SQAURE
    MOV BL,1; INTIALIAZATION FOR OUTER LOOP
    MOV CL,1; INTIALIZATION FOR INNER LOOP
    
    FOR1:
    CMP BL,BH
    JG EXIT_FOR1
    
    FOR2:
    CMP CL,BH
    JG EXIT_FOR2
    PRINT "*"
    INC CL
    JMP FOR2
    
    EXIT_FOR2:
    INC BL
    MOV CL,1
    PRINTN ""
    JMP FOR1
    
    EXIT_FOR1:
    MOV AH,4CH
    INT 21H  
    MAIN ENDP
ENDP